version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "8080:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=llama3.2
      - OLLAMA_API_TEMPERATURE=0.7
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
      - PORT=8080
      - chat.cors.allowed-origins=http://localhost:3000
      - chat.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
      - chat.cors.allowed-headers=*
      - chat.cors.allow-credentials=true
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
    environment:
      - OLLAMA_MODEL=llama3.2

volumes:
  ollama_data: 